module.exports = {
  apps: [
    {
      name: 'main',
      cwd: './apps/main',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3000, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'notes',
      cwd: './apps/notes',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3001, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'journey',
      cwd: './apps/journey',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3002, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'todo',
      cwd: './apps/todo',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3003, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'health',
      cwd: './apps/health',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3004, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'moments',
      cwd: './apps/moments',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3005, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'grow',
      cwd: './apps/grow',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3006, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'pulse',
      cwd: './apps/pulse',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3007, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'fit',
      cwd: './apps/fit',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3008, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'projects',
      cwd: './apps/projects',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3009, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'workflow',
      cwd: './apps/workflow',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3010, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'calendar',
      cwd: './apps/calendar',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3014, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    },
    {
      name: 'admin',
      cwd: './apps/admin',
      script: 'pnpm',
      args: 'dev',
      env: { PORT: 3020, NODE_ENV: 'development' },
      watch: ['app', 'components', 'lib', 'src', 'pages'],
      ignore_watch: ['node_modules', '.next', '*.log'],
      watch_delay: 1000,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: 5000,
      exp_backoff_restart_delay: 100
    }
  ]
};
